spring.application.name=prosjekt
server.port=8080
app.public-base-url=${APP_PUBLIC_BASE_URL:http://localhost:8080}

vaadin.launch-browser=false

spring.datasource.url=${DATABASE_URL:jdbc:postgresql://localhost:5432/havbruksbrukt}
spring.datasource.username=${DATABASE_USERNAME:havbruksbrukt}
spring.datasource.password=${DATABASE_PASSWORD:havbruksbrukt}
spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.query.fail_on_pagination_over_collection_fetch=true
spring.jpa.properties.hibernate.default_batch_fetch_size=50
